<h1>About me</h1>

<p>I grew up in the picturesque village of Govilon (near Abergavenny) before moving west for four years to complete a Masters degree in Computer Science at <a title="Swansea University, Computer Science Department website" href="http://www.swan.ac.uk/compsci">Swansea</a> University.  In that time, I studied a wide variety of subjects from software engineering, to computer hardware and the theory of programming languages.  I also spent a year working on industry projects, human-computer interaction, search engines and business management.</p>
<p>At the same time I worked as a freelance web developer, producing sites for a range of companies, organisations and educational establishments such as Hereford Sixth Form College and Govilon Heritage.  I also worked part time as a developer for a web development company in Cardiff.  While there, I was involved in developing and maintaining websites for companies such as Thomas Cook, Neilson and the Welsh Sports Association.</p>
<p>Outside of work and my studies, I was heavily involved in the development of a website for the Swansea Student Union&#8217;s newspaper &#8211; The Waterfront.  Through this I was involved in online reporting, editing, and responsible for the 2008 sabbatical elections coverage (including real-time blogging, interviews and photography).</p>
<p>Following my degree, I worked as the lead developer for <a href="http://www.cflabs.org.uk">CF Labs</a> at Consumer Focus.  The team was responsible for designing and producing online consumer empowerment tools, opening up public datasets and making them easy to understand.</p>
<p>I now work as a Tech Arch at the <a href="https://gds.blog.gov.uk">Government Digital Service</a>. Here I've been working on building the new single website for government - <a href="https://www.gov.uk">GOV.UK</a> - and on transforming government transactions.</p>
<p>As a committee member of the <a title="The Govion Heritage group website" href="http://www.govilon.com/govilonheritage/">Govilon Heritage</a> Group, I&#8217;ve been involved in promoting the history of my village through developing information boards, historical trails and guided walks which run every few months.</p>
<p>I love travelling and have visited many different places, including Belgium, France, Greece, Egypt, Israel and Turkey.   Time permitting, I hope to get the chance to visit Japan sometime over the next few years &#8211; the combination of technology and sushi sounds ideal! Despite this, I&#8217;m proud to be Welsh, even if hardly anyone English can pronounce my name.</p>
<p>If you want to know more about me, you can follow me on Twitter at <a title="Dafydd's twitter page" href="https://twitter.com/dafyddbach">twitter.com/dafyddbach</a> or leave me a comment on one of my blog posts.</p>
