<p>I'm the founder of <a href="https://www.cedyrn.com">Cedyrn</a> - a consultancy set up to advise large organisations on replacement of legacy technology, adoption of public cloud services, and how to build strong digital teams. I'm also an affiliate at <a href="https://www.public.digital">Public Digital</a>, helping governments and organisations around the world adapt to the internet era.</p>

<p>I've spent the last few years helping organisations such as the Ministry of Justice manage the growing problem of unsustainable and complex legacy technology. I developed the strategy and led the teams to modernise and move the systems supporting Legal Aid to public cloud. I've supported the development of a new digital strategy at the Crown Commercial Service, and I've coached C-Suite executives at a €15bn global company.</p>

<p>Previously, I was a co-founder at the UK <a href="https://gds.blog.gov.uk">Government Digital Service</a>. I worked on the launch of <a href="https://www.gov.uk">GOV.UK</a>, the <a href="https://www.gov.uk/design-principles">GDS Design Principles</a>, <a href="https://www.gov.uk/service-manual">Service Manual</a> and <a href="https://www.gov.uk/service-manual/service-standard">Digital Service Standard</a>.</p>

<p>Following the publication of the first <a href="https://www.gov.uk/government/collections/government-digital-strategy-reports-and-research">Government Digital Strategy</a>, I spent several years working closely with government departments to support their digital transformation. I helped deliver new digital services such as <a href="https://www.gov.uk/view-driving-licence">view your driving licence</a>, <a href="https://www.gov.uk/sold-bought-vehicle">buy and sell vehicles</a> and <a href="https://www.gov.uk/vehicle-tax">tax your vehicle</a>. I also led teams that transitioned DVLA's IT services <a href="https://gds.blog.gov.uk/2015/10/02/its-all-about-people-dvla-delivers-real-transformation/">back in-house</a>.</p>

<p>I returned to GDS in 2016 to head up technology on GOV.UK. I sat as a member of the Cabinet Office Technology Spend Control Board, and was a lead assessor for the Digital Service Standard.</p>

<p>I have over 10 years experience in technology, digital product management and transformation. I've developed consumer rights tools for Consumer Focus and large technology systems for Thomas Cook. I have a masters degree in Human Computer Interaction.</p>
